name: Run Go App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-go-app:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23

    - name: Install dependencies
      run: go mod tidy

    - name: Run the application
      env:
        RECEIPT_CHANNEL_ID: ${{ secrets.RECEIPT_CHANNEL_ID }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      run: go run .
